---
sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
env:
  matrix:
    - EMBER_VERSION=default
matrix:
  fast_finish: true

services:
  - mysql

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - cd acm-manager-web-application 
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - mysql -e 'CREATE DATABASE acm;'

install:
  - npm install
  - bower install
  - mysql acm < ../acm_Database_Create.sql
  - mysql acm < ../acm_Database_Placeholder.sql

script:
  - ember try:one $EMBER_VERSION --skip-cleanup=true --- ember test --reporter dot
    
