---
sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
env:
  matrix:
    - EMBER_VERSION=default
matrix:
  fast_finish: true
    
cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - cd acm-manager-web-application 
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_VERSION --skip-cleanup=true --- ember test --reporter dot
    
